<template>
    <div class="tooltip" >
      <span
        v-if="显示提示"
        :style="`position:fixed;left:${当前鼠标坐标.x + 10}px;top: ${当前鼠标坐标.y + 10}px;z-index:251`"
        >{{当前提示内容}}</span>
    </div>
</template>
<script>
module.exports={
    name:"cc-tooltip",
    props:["当前鼠标坐标"],
    data(){
        return{
            当前提示内容:"测试",
            显示提示:false
        }
    },
    mounted(){
        this.$事件总线.$on("显示提示",($event)=>this.开始显示提示($event))
        this.$事件总线.$on("提示内容改变",this.提示内容改变)
        this.$事件总线.$on("隐藏提示",this.隐藏提示)
        this.$事件总线.$emit("显示提示")
    },
    methods:{
      开始显示提示($event){
        //  console.log("显示提示")
          this.当前提示内容=$event
          this.显示提示=true
      },
      提示内容改变($event){
          this.当前提示内容=$event
      },
      隐藏提示($event){
          this.显示提示=false
      }
    }
}
</script>